name: supertuxkart
version: '0.9.3'
icon: supertuxkart.png
summary: SuperTuxKart is a free kart racing game
description: >
  SuperTuxKart is a free kart racing game. It focuses on fun and not on
  realistic kart physics. Instructions can be found on the in-game help page.

  The SuperTuxKart homepage can be found at https://supertuxkart.net/.

  To run SuperTuxKart, make sure that your computer includes a graphics card
  capable of 3D rendering - NVIDIA GeForce 8 series and newer (GeForce 8100 or
  newer), AMD/ATI Radeon HD 4000 series and newer, Intel HD Graphics 3000 and
  newer. You'll need at least 512 MB of free VRAM (video memory), and a CPU
  that's running at 1 GHz or faster.

grade: stable
confinement: strict

apps:
  supertuxkart:
    command: desktop-launch alsa-launch libopenh264-launch $SNAP/usr/bin/supertuxkart
    desktop: usr/share/applications/supertuxkart.desktop
    environment:
      SUPERTUXKART_DATADIR: $SNAP/usr/share/supertuxkart
    plugs:
    - desktop
    - joystick
    - network
    - opengl
    - pulseaudio
    - wayland
    - x11

parts:
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-plugins:
    after: [alsa-lib]

  libopenh264-helper:
    source: libopenh264-helper
    source-subdir: libopenh264
    plugin: make
    stage-packages:
    - bzip2
    - curl
    prime:
    - bin/bunzip2
    - bin/libopenh264-launch
    - usr/bin/curl
    - usr/lib/**/libasn1*
    - usr/lib/**/libcurl-gnutls*
    - usr/lib/**/libgssapi.so*
    - usr/lib/**/libhcrypto*
    - usr/lib/**/libheimbase*
    - usr/lib/**/libheimntlm*
    - usr/lib/**/libhx509*
    - usr/lib/**/liblber*
    - usr/lib/**/libldap*
    - usr/lib/**/libroken*
    - usr/lib/**/librtmp*
    - usr/lib/**/libsasl2*
    - usr/lib/**/libwind*
    - usr/lib/**/sasl2
    build-attributes: [no-system-libraries]

  libopenh264-library:
    after: [alsa, libopenh264-helper]
    plugin: make
    make-parameters:
    - PREFIX=/usr
    source: https://github.com/cisco/openh264/archive/v1.7.0.tar.gz
    build-packages:
    - g++
    - libpulse-dev
    - nasm
    stage-packages: [libpulse0]
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig -name "*openh264*.pc" -exec \
        sed -i "s|/usr/include|$SNAPCRAFT_STAGE/usr/include|g;s|/usr/lib|$SNAPCRAFT_STAGE/usr/lib|g" '{}' \;
    prime:
    - lib/libjson-c*
    - lib/libwrap*
    - usr/lib/**/libasyncns*
    - usr/lib/**/libFLAC*
    - usr/lib/**/libpulse*
    - usr/lib/**/libsndfile*
    - usr/lib/**/libvorbisenc*
    - usr/lib/**/pulseaudio
    - usr/local/lib/libopenh264.so*
    build-attributes: [no-system-libraries]

  libopenglrecorder:
    after: [libopenh264-library]
    plugin: cmake
    source: https://github.com/Benau/libopenglrecorder.git
    source-depth: 1
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
    - libturbojpeg
    - libogg-dev
    - libpulse-dev
    - libvorbis-dev
    - libvpx-dev
    stage-packages:
    - libturbojpeg
    - libogg0
    - libpulse0
    - libvorbisenc2
    - libvpx3

  supertuxkart-code:
    after:
    - desktop-glib-only
    - libopenglrecorder
    - libopenh264-library
    plugin: cmake
    source: https://sourceforge.mirrorservice.org/s/su/supertuxkart/SuperTuxKart/$SNAPCRAFT_PROJECT_VERSION/supertuxkart-$SNAPCRAFT_PROJECT_VERSION-src.tar.xz
    override-build: |
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/128x128/apps/supertuxkart.png|' ../src/data/supertuxkart.desktop
      snapcraftctl build
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DENABLE_WAYLAND_DEVICE=ON
    build-packages:
    - libbluetooth-dev
    - libcurl4-openssl-dev
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libfribidi-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libogg-dev
    - libopenal-dev
    - libpng-dev
    - libpulse-dev
    - libvorbis-dev
    - libxrandr-dev
    - libwayland-dev
    - libxkbcommon-dev
    - subversion
    - zlib1g-dev
    stage-packages:
    - libbluetooth3
    - libcurl3
    - libdb5.3
    - libfreetype6
    - libfribidi0
    - libgl1-mesa-glx
    - libjpeg8
    - libogg0
    - libopenal1
    - libpng16-16
    - libpulse0
    - libvorbis0a
    - libvorbisfile3
    - libxrandr2
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1-mesa
    - libxkbcommon0
    - zlib1g
    prime:
    - lib
    - usr/bin/supertuxkart
    - usr/lib
    - -usr/lib/gcc
    - -usr/lib/sasl2
    - usr/share/appdata
    - usr/share/applications
    - usr/share/icons
    - usr/share/pixmaps
    - usr/share/supertuxkart
    - usr/share/X11
    build-attributes: [no-system-libraries]
